// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././reducedOld.proto
package com.levelmoney.proto.reducedTest.old;

import com.squareup.wire.Message;

public final class DataObject extends Message {
  private static final long serialVersionUID = 0L;

  public DataObject() {
  }

  private DataObject(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof DataObject;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<DataObject> {

    public Builder() {
    }

    public Builder(DataObject message) {
      super(message);
    }

    @Override
    public DataObject build() {
      return new DataObject(this);
    }
  }
}
