// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././reducedOld.proto
package com.levelmoney.proto.reducedTest.old;

import com.squareup.wire.Message;

public final class Fund extends Message {
  private static final long serialVersionUID = 0L;

  public Fund() {
  }

  private Fund(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof Fund;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<Fund> {

    public Builder() {
    }

    public Builder(Fund message) {
      super(message);
    }

    @Override
    public Fund build() {
      return new Fund(this);
    }
  }
}
