// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././reducedOld.proto
package com.levelmoney.proto.reducedTest.old;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class Response extends Message {
  private static final long serialVersionUID = 0L;

  @ProtoField(tag = 1)
  public final DataObject data;

  public Response(DataObject data) {
    this.data = data;
  }

  private Response(Builder builder) {
    this(builder.data);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Response)) return false;
    return equals(data, ((Response) other).data);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = data != null ? data.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<Response> {

    public DataObject data;

    public Builder() {
    }

    public Builder(Response message) {
      super(message);
      if (message == null) return;
      this.data = message.data;
    }

    public Builder data(DataObject data) {
      this.data = data;
      return this;
    }

    @Override
    public Response build() {
      return new Response(this);
    }
  }
}
