// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././reducedOld.proto
package com.levelmoney.proto.reducedTest.old;

import com.squareup.wire.Message;

public final class Transaction extends Message {
  private static final long serialVersionUID = 0L;

  public Transaction() {
  }

  private Transaction(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof Transaction;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<Transaction> {

    public Builder() {
    }

    public Builder(Transaction message) {
      super(message);
    }

    @Override
    public Transaction build() {
      return new Transaction(this);
    }
  }
}
