// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././reducedNew.proto
package com.levelmoney.proto.reducedTest.updated;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class BudgetResponse extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<Fund> DEFAULT_EXPENSES = Collections.emptyList();

  @ProtoField(tag = 16, label = REPEATED, messageType = Fund.class)
  public final List<Fund> expenses;

  public BudgetResponse(List<Fund> expenses) {
    this.expenses = immutableCopyOf(expenses);
  }

  private BudgetResponse(Builder builder) {
    this(builder.expenses);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BudgetResponse)) return false;
    return equals(expenses, ((BudgetResponse) other).expenses);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = expenses != null ? expenses.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<BudgetResponse> {

    public List<Fund> expenses;

    public Builder() {
    }

    public Builder(BudgetResponse message) {
      super(message);
      if (message == null) return;
      this.expenses = copyOf(message.expenses);
    }

    public Builder expenses(List<Fund> expenses) {
      this.expenses = checkForNulls(expenses);
      return this;
    }

    @Override
    public BudgetResponse build() {
      return new BudgetResponse(this);
    }
  }
}
