// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././reducedNew.proto
package com.levelmoney.proto.reducedTest.updated;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class Fund extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<Transaction> DEFAULT_SEEN_TRANSACTIONS_THIS_MONTH = Collections.emptyList();

  @ProtoField(tag = 201, label = REPEATED, messageType = Transaction.class)
  public final List<Transaction> seen_transactions_this_month;

  public Fund(List<Transaction> seen_transactions_this_month) {
    this.seen_transactions_this_month = immutableCopyOf(seen_transactions_this_month);
  }

  private Fund(Builder builder) {
    this(builder.seen_transactions_this_month);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Fund)) return false;
    return equals(seen_transactions_this_month, ((Fund) other).seen_transactions_this_month);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = seen_transactions_this_month != null ? seen_transactions_this_month.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<Fund> {

    public List<Transaction> seen_transactions_this_month;

    public Builder() {
    }

    public Builder(Fund message) {
      super(message);
      if (message == null) return;
      this.seen_transactions_this_month = copyOf(message.seen_transactions_this_month);
    }

    public Builder seen_transactions_this_month(List<Transaction> seen_transactions_this_month) {
      this.seen_transactions_this_month = checkForNulls(seen_transactions_this_month);
      return this;
    }

    @Override
    public Fund build() {
      return new Fund(this);
    }
  }
}
