// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././reducedNew.proto
package com.levelmoney.proto.reducedTest.updated;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class Response extends Message {
  private static final long serialVersionUID = 0L;

  @ProtoField(tag = 1)
  public final DataObject expenses;

  public Response(DataObject expenses) {
    this.expenses = expenses;
  }

  private Response(Builder builder) {
    this(builder.expenses);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Response)) return false;
    return equals(expenses, ((Response) other).expenses);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = expenses != null ? expenses.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<Response> {

    public DataObject expenses;

    public Builder() {
    }

    public Builder(Response message) {
      super(message);
      if (message == null) return;
      this.expenses = message.expenses;
    }

    public Builder expenses(DataObject expenses) {
      this.expenses = expenses;
      return this;
    }

    @Override
    public Response build() {
      return new Response(this);
    }
  }
}
